# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'symmetry-lab-mila'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-204831507-4'

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/excitingtimes/symmetry-lab-mila'}
- {icon: 'envelope',   link: 'mailto:siamak@cs.mcgill.ca'}
- {icon: 'rss-square', link: '/feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer posts'
  previous_page: 'Older posts'

sharing_button_prompt: 'Feel free to share !'

related_posts: 'You may also enjoy :'

post_date_prefix: 'Written on'
