# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'excitingtimes'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-204831507-1'

menu:
- {name: 'About',   url: 'about.html'}
- {name: 'Blog', url: 'blog.html'}
- {name: 'Publications', url: 'papers.html'}
- {name: 'Teaching', url: 'teaching.html'}
- {name: 'Podcast', url: 'podcast.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/hugoby42'}
- {icon: 'twitter',    link: 'https://twitter.com/volut3s'}
- {icon: 'facebook',    link: 'https://facebook.com/exciting-times'}
- {icon: 'linkedin',   link: 'http://www.linkedin.com/in/hugo42/'}
- {icon: 'envelope',   link: 'mailto:hugo.sonnery@mail.mcgill.ca'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer posts'
  previous_page: 'Older posts'

sharing_button_prompt: 'Feel free to share !'

related_posts: 'You may also enjoy :'

post_date_prefix: 'Written on'
